### ISSUE TITLE
[FEATURE] Basic Frontend

### ISSUE THREAD

**Issue by srkds** [srkds/sabha#22]
**Additional context**
The first version of the front-end. With bare minimum UI with functionality.

**Subtasks**
- [ ] Login Page (Issue: ) (PR: )
- [ ] Registration Page (Issue: ) (PR: )
- [ ] Home Page (Dashboard) (Issue: ) (PR: )
- [ ] Create Poll Page (Issue: ) (PR: )
- [ ] Individual Poll Page (Issue: ) (PR: )
- [ ] Vote Page (Issue: ) (PR: )

**Comment by dhruvilxcode** [comment]
Use [TailwindCSS](https://tailwindcss.com/), Your Frontend will look good, in less time.

**Comment by srkds** [comment]
Hi @dhruvilxcode 
I appreciate your suggestion
Will consider TailwindCSS.

Thank you
